<link href="/assets/css/slick.css" rel="stylesheet" media="all">
<link href="/assets/css/slick-theme.css" rel="stylesheet" media="all">
<link href="/assets/css/animate.css" rel="stylesheet" media="all">
<link href="/assets/css/magnific-popup.css" rel="stylesheet" media="all">
<link href="/assets/css/check.css" rel="stylesheet" media="all">
<link href="/assets/css/styles.css" rel="stylesheet" media="all">