<script src="//ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="/assets/js/jquery.min.js"><\/script>');</script>
<script src="/assets/js/modernizr.min.js"></script>
<script src="/assets/js/slick.min.js"></script>
<script src="/assets/js/wow.min.js"></script>
<script src="/assets/js/jquery.magnific-popup.min.js"></script>
<script src="/assets/js/scripts.js"></script>